"""No PII in the public repo — executable policy, not a convention.

Three layers:
1. A token denylist of personal names that must never appear. Stored as
   SHA-256 hashes so the policy itself doesn't reintroduce the name.
2. E-mail addresses only in allowlisted files that are known-synthetic
   (generated fixtures) or use obviously fake domains.
3. Private artifacts (real exports, user config, uploads) must never be
   git-tracked, whatever .gitignore says today.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# sha256(lowercased token) of names/identifiers that must not appear.
# To extend: python3 -c "import hashlib; print(hashlib.sha256(b'<token>').hexdigest())"
FORBIDDEN_TOKEN_HASHES = {
    "efee614420c57ddd2a8e91eeef6f6b83d5356c2288155be0f273bef986e3b850",
    "21cba5305aa67d1ff3cb6201861dced35ae83a07ab21145b5f653deefafcf3e1",
    "cf053e58394c10c65e4923131e4279a8c06bafdf807aa9e097eca15dc20b4b22",
    "8353773cc3bb4b5031561324570be283495d6e825c6067ceb3de980b32e9f4fc",
    "314e322f94349cb7151880ae279f70d9fd3e1104ee7231f437fd46d327e288ff",
}

# files where e-mail-shaped strings are fine (synthetic data + test fixtures)
EMAIL_ALLOWLIST = {
    "data/sample_eshop.csv",       # generated by gen/ — no real customers
    "gen/synth.py",                # the generator's templates
}
FAKE_DOMAIN = re.compile(r"@(x|y|example)\.[a-z]{2,}$|@seznam\.cz$|@(gmail|email)\.(com|cz)$")

# path fragments that must never be tracked
PRIVATE_PATHS = ("bq_export", "data/uploads", "config/segsmart.json")

EMAIL = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}")
BIRTH_NUMBER = re.compile(r"\b\d{6}/\d{3,4}\b")        # czech rodné číslo
TOKEN = re.compile(r"\w+", re.UNICODE)


def _tracked_files():
    out = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True,
                         text=True, check=True).stdout.splitlines()
    return [f for f in out if not f.endswith((".png", ".parquet", ".zip"))]


def _read(rel):
    try:
        return (REPO / rel).read_text(encoding="utf-8", errors="replace")
    except (IsADirectoryError, FileNotFoundError):    # symlinks / deleted
        return ""


def test_no_forbidden_names():
    hits = []
    for rel in _tracked_files():
        tokens = {t.lower() for t in TOKEN.findall(_read(rel))}
        for t in tokens:
            if hashlib.sha256(t.encode()).hexdigest() in FORBIDDEN_TOKEN_HASHES:
                hits.append(f"{rel}: token {t[0]}***")
    assert not hits, f"forbidden personal names found: {hits}"


def test_emails_only_synthetic():
    hits = []
    for rel in _tracked_files():
        if rel in EMAIL_ALLOWLIST:
            continue
        for m in EMAIL.findall(_read(rel)):
            if not FAKE_DOMAIN.search(m):
                hits.append(f"{rel}: {m}")
    assert not hits, f"real-looking e-mail addresses in tracked files: {hits}"


def test_no_birth_numbers():
    hits = [rel for rel in _tracked_files()
            if rel not in EMAIL_ALLOWLIST and BIRTH_NUMBER.search(_read(rel))]
    assert not hits, f"birth-number-shaped strings: {hits}"


def test_demo_result_is_anonymized():
    """The tracked demo result ships per-customer rows — ids must be anonymized
    (never e-mail-shaped) and the contact fields must be empty. A run on a real
    shop fills `email`/`name` with customer PII; persisting that into the tracked
    demo file would leak it, so this test is the tripwire that catches it before
    a commit (it reads the on-disk file, which a real run overwrites)."""
    res = (REPO / "out/result.json")
    if not res.exists():
        return
    data = json.loads(res.read_text(encoding="utf-8"))
    for c in data.get("customers", []):
        assert not EMAIL.search(c["id"]), f"email-shaped id in demo: {c['id']}"
        email = c.get("email", "")
        assert email == "" or FAKE_DOMAIN.search(email), \
            f"real-looking customer e-mail in tracked demo: {email}"
        assert not c.get("name"), \
            f"customer name in tracked demo result (real-shop PII?): {c.get('name')!r}"


def test_private_artifacts_not_tracked():
    tracked = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True,
                             text=True, check=True).stdout
    hits = [p for p in PRIVATE_PATHS if p in tracked]
    assert not hits, f"private artifacts are git-tracked: {hits}"
